import { Database } from '@/database.types'

// Define the possible schema types
type SchemaType = 'api'

export let insertType_tblCRMContact: Database[SchemaType]['Tables']['s$tblCRMContact']['Insert']
export let insertType_tblLoanApplication: Database[SchemaType]['Tables']['tblLoanApplication']['Insert']
export let insertType_tblClient: Database[SchemaType]['Tables']['s$tblClient']['Insert']
export let insertType_tblClientAddress: Database[SchemaType]['Tables']['s$tblClientAddress']['Insert']
export let insertType_tblClientBankruptcy: Database[SchemaType]['Tables']['s$tblClientBankruptcy']['Insert']
export let insertType_tblClientBenefitDetails: Database[SchemaType]['Tables']['s$tblClientBenefitDetails']['Insert']
export let insertType_tblClientBenefits: Database[SchemaType]['Tables']['s$tblClientBenefits']['Insert']
export let insertType_tblClientEmail: Database[SchemaType]['Tables']['s$tblClientEmail']['Insert']
export let insertType_tblClientEmployment: Database[SchemaType]['Tables']['s$tblClientEmployment']['Insert']
export let insertType_tblClientExtension: Database[SchemaType]['Tables']['s$tblClientExtension']['Insert']
export let insertType_tblClientIdentifications: Database[SchemaType]['Tables']['s$tblClientIdentifications']['Insert']
export let insertType_tblClientIncome: Database[SchemaType]['Tables']['s$tblClientIncome']['Insert']
export let insertType_tblClientKYCQuestions: Database[SchemaType]['Tables']['s$tblClientKYCQuestions']['Insert']
export let insertType_tblClientNonNZTaxInformation: Database[SchemaType]['Tables']['s$tblClientNonNZTaxInformation']['Insert']
export let insertType_tblClientPersonalDetails: Database[SchemaType]['Tables']['s$tblClientPersonalDetails']['Insert']
export let insertType_tblClientPhone: Database[SchemaType]['Tables']['s$tblClientPhone']['Insert']
export let insertType_tblClientRetirement: Database[SchemaType]['Tables']['s$tblClientRetirement']['Insert']
export let insertType_tblClientSchoolsOrTertiaryInstitutions: Database[SchemaType]['Tables']['s$tblClientSchoolsOrTertiaryInstitutions']['Insert']
export let insertType_tblClientTaxStatus: Database[SchemaType]['Tables']['s$tblClientTaxStatus']['Insert']
export let insertType_tblClientUnemployment: Database[SchemaType]['Tables']['s$tblClientUnemployment']['Insert']
export let insertType_tblClientWorkVisaDetails: Database[SchemaType]['Tables']['s$tblClientWorkVisaDetails']['Insert']
export let insertType_tblVehicleSecurity: Database[SchemaType]['Tables']['tblVehicleSecurity']['Insert']
export let insertType_tblLoanApplicationFinancialDetails: Database[SchemaType]['Tables']['tblLoanApplicationFinancialDetails']['Insert']
export let insertType_tblCreditSenseForApplication: Database[SchemaType]['Tables']['tblCreditSenseForApplication']['Insert']
export let insertType_tblFrequencyTypes: Database[SchemaType]['Tables']['tblFrequencyTypes']['Insert']
export let insertType_tblMembershipApplicationDetails: Database[SchemaType]['Tables']['tblMembershipApplicationDetails']['Insert']
export let insertType_tblMembershipStaffPortalErrorLogs: Database[SchemaType]['Tables']['tblMembershipStaffPortalErrorLogs']['Insert']
export let insertType_tblSchoolsAndTertiaryInstitutions: Database[SchemaType]['Tables']['tblSchoolsAndTertiaryInstitutions']['Insert']

export let updateType_tblCRMContact: Database[SchemaType]['Tables']['s$tblCRMContact']['Update']
export let updateType_tblLoanApplication: Database[SchemaType]['Tables']['tblLoanApplication']['Update']
export let updateType_tblClient: Database[SchemaType]['Tables']['s$tblClient']['Update']
export let updateType_tblClientAddress: Database[SchemaType]['Tables']['s$tblClientAddress']['Update']
export let updateType_tblClientBankruptcy: Database[SchemaType]['Tables']['s$tblClientBankruptcy']['Update']
export let updateType_tblClientBenefitDetails: Database[SchemaType]['Tables']['s$tblClientBenefitDetails']['Update']
export let updateType_tblClientBenefits: Database[SchemaType]['Tables']['s$tblClientBenefits']['Update']
export let updateType_tblClientEmail: Database[SchemaType]['Tables']['s$tblClientEmail']['Update']
export let updateType_tblClientEmployment: Database[SchemaType]['Tables']['s$tblClientEmployment']['Update']
export let updateType_tblClientExtension: Database[SchemaType]['Tables']['s$tblClientExtension']['Update']
export let updateType_tblClientIdentifications: Database[SchemaType]['Tables']['s$tblClientIdentifications']['Update']
export let updateType_tblClientIncome: Database[SchemaType]['Tables']['s$tblClientIncome']['Update']
export let updateType_tblClientKYCQuestions: Database[SchemaType]['Tables']['s$tblClientKYCQuestions']['Update']
export let updateType_tblClientNonNZTaxInformation: Database[SchemaType]['Tables']['s$tblClientNonNZTaxInformation']['Update']
export let updateType_tblClientPersonalDetails: Database[SchemaType]['Tables']['s$tblClientPersonalDetails']['Update']
export let updateType_tblClientPhone: Database[SchemaType]['Tables']['s$tblClientPhone']['Update']
export let updateType_tblClientRetirement: Database[SchemaType]['Tables']['s$tblClientRetirement']['Update']
export let updateType_tblClientSchoolsOrTertiaryInstitutions: Database[SchemaType]['Tables']['s$tblClientSchoolsOrTertiaryInstitutions']['Update']
export let updateType_tblClientTaxStatus: Database[SchemaType]['Tables']['s$tblClientTaxStatus']['Update']
export let updateType_tblClientUnemployment: Database[SchemaType]['Tables']['s$tblClientUnemployment']['Update']
export let updateType_tblClientWorkVisaDetails: Database[SchemaType]['Tables']['s$tblClientWorkVisaDetails']['Update']
export let updateType_tblVehicleSecurity: Database[SchemaType]['Tables']['tblVehicleSecurity']['Update']
export let updateType_tblLoanApplicationFinancialDetails: Database[SchemaType]['Tables']['tblLoanApplicationFinancialDetails']['Update']
export let updateType_tblCreditSenseForApplication: Database[SchemaType]['Tables']['tblCreditSenseForApplication']['Update']
export let updateType_tblFrequencyTypes: Database[SchemaType]['Tables']['tblFrequencyTypes']['Update']
export let updateType_tblMembershipApplicationDetails: Database[SchemaType]['Tables']['tblMembershipApplicationDetails']['Update']
export let updateType_tblMembershipStaffPortalErrorLogs: Database[SchemaType]['Tables']['tblMembershipStaffPortalErrorLogs']['Update']
export let updateType_tblSchoolsAndTertiaryInstitutions: Database[SchemaType]['Tables']['tblSchoolsAndTertiaryInstitutions']['Update']

export let insertType_tblMembershipApplicationErrors: Database[SchemaType]['Tables']['tblMembershipApplicationErrors']['Insert']

export let rowType_tblLoanPurposeCodes: Database[SchemaType]['Tables']['tblLoanPurposeCodes']['Row']
export let rowType_tblIdentificationsCodes: Database[SchemaType]['Tables']['tblIdentificationsCodes']['Row']
export let rowType_tblEmploymentTypes: Database['public']['Tables']['tblEmploymentTypes']['Row']
export let rowType_tblOccupation: Database['public']['Tables']['tblOccupation']['Row']
export let rowType_tblTypesofBenefits: Database['public']['Tables']['tblTypesofBenefits']['Row']
export let rowType_tblSchoolsAndTertiaryInstitutions: Database['public']['Tables']['tblSchoolsAndTertiaryInstitutions']['Row']
export let rowType_tblVehicleSecurity: Database[SchemaType]['Tables']['tblVehicleSecurity']['Row']
export let rowType_tblLoanApplicationFinancialDetails: Database[SchemaType]['Tables']['tblLoanApplicationFinancialDetails']['Row']
export let rowType_tblCreditSenseForApplication: Database[SchemaType]['Tables']['tblCreditSenseForApplication']['Row']
