export const primeRawJson = {
  data: {
    type: 'applications',
    attributes: {
      applicationName: 'Online Submission',
      clientApplication: 'FCUWEBAPP',
      comparisonRatesSupplied: 'N',
      externalSystemReference: 'ONL_kjmNWvoESz',
      draft: 'N',
      bossType: 'FCUONPLAP',
      customAttributes: [],
      financialDetails: [
        {
          advance: 'N',
          balloonAmount: 0,
          balloonPercent: 0,
          commissionAmount: 0,
          deposit: {
            bond: 0,
            cashRefund: 0,
            depositAmount: 0,
            payoutAmount: 0,
            tradeInAmount: 0,
          },
          fees: {
            capitalised: 0,
            fee: [
              {
                amount: 4.6,
                capitalised: 'Y',
                code: 'LCRFA',
                gstAmount: 0,
                seq: '1',
              },
              {
                amount: 3.4,
                capitalised: 'Y',
                code: 'LCRFB',
                gstAmount: 0,
                seq: '1',
              },
              {
                amount: 3,
                capitalised: 'Y',
                code: 'LCRFC',
                gstAmount: 0,
                seq: '1',
              },
              {
                amount: 0.25,
                capitalised: 'Y',
                code: 'LCRFD',
                gstAmount: 0,
                seq: '1',
              },
              {
                amount: 4.5,
                capitalised: 'Y',
                code: 'LCRFE',
                gstAmount: 0,
                seq: '1',
              },
              {
                amount: 2.72,
                capitalised: 'Y',
                code: 'LCRFF',
                gstAmount: 0,
                seq: '1',
              },
              {
                amount: 8.05,
                capitalised: 'Y',
                code: 'LCRFG',
                gstAmount: 0,
                seq: '1',
              },
            ],
            nonCapitalised: 0,
            refresh: 'Y',
          },
          insurances: { insurance: [] },
          interestRateStructure: {
            initialRate: { rateType: 'VARIABLE', baseRate: 'PL', margin: 0 },
          },
          paymentFrequencyType: { code: 'M', description: 'MONTHLY' },
          paymentFrequencyUnit: 1,
          paymentMethod: { paymentMethod: 'AUTOPAY' },
          product: 'PERN',
          purchasePrice: {
            accessories: 0,
            retailPrice: null,
            total: null,
            lct: 0,
          },
          reapplyDefaults: null,
          residualValue: 0,
          seq: '1',
          settlementDate: '2025-04-27T00:00:00Z',
          signatureDate: '2025-04-27T00:00:00Z',
          taxTreatment: null,
          term: 36,
          termType: 'M',
          valueOfAdvInstalment: 0,
        },
      ],
      loadedByClientNumber: '0000148335',
      loanPurpose: { level1: 'NBUS', level2: 'TRVL' },
      memoMaint: {
        memo: { refType: 'ASSIGN' },
        memoLines: {
          text: [
            '',
            'Promo Code: N/A',
            '',
            '------ Credit Sense ------',
            '',
            'Reference: null',
            '',
            '------ Provident Credit Care ------',
            '',
            'Provident Premium: undefined',
          ],
        },
        severity: '00',
        subject: 'Online Application Declaration',
      },
      originator: { clientNumber: '0003000100', value: '0003000100' },
      owner: '0000148335',
      recourseAccount: 'Y',
      salesChannel: 'INTERNET',
      salutation: 'N',
      subPrime: 'N',
      taxRegion: null,
      accountManager: null,
      openingBranch: { value: 'VIR', unitType: 'B', unitId: 'VIR' },
      tradingBranch: 'VIR',
      type: 'D',
    },
    relationships: {
      associatedClients: {
        data: [{ id: '0001022184', type: 'associatedClients' }],
      },
      securities: { data: [{ type: 'securities', id: '0000299612' }] },
    },
  },
  included: [
    {
      type: 'associatedClients',
      id: '0001022184',
      attributes: {
        role: 'PRIMEB',
        seq: '1',
        signatureRequired: 'M',
        creditCheckAuthorised: 'N',
        order: '1',
        clientReference: null,
        clientMaint: {
          clientID: '0001022184',
          generalDetails: {
            externalSystemReference: '',
            clientType: 'I',
            status: { code: 'A' },
            gna: 'N',
            existingClient: 'Y',
            defaultManager: '0000148335',
            individualDetails: {
              title: 'Mr',
              forename: 'Isaac',
              surname: 'Vicliph',
              clientOtherNamesExist: 'N',
              gender: 'Male',
              dateOfBirth: '2007-08-01',
              dateOfBirthRefused: 'N',
              maritalStatus: 'S',
              countryOfResidence: 'NZ',
              countryOfCitizenship: 'NZ',
              numberOfDependants: '2',
              numberOfAdults: '1',
              accommodation: {
                code: 'RNT2',
                description: 'Renting less than 2',
              },
              resident: 'Y',
              smoker: 'N',
            },
          },
          clientIdentifications: {},
          contactDetails: {
            address: [],
            phone: [],
            mobile: [],
            email: [
              {
                address: 'samisaac75@gmail.com',
                preferredMethod: 'Y',
                effectiveDate: '2025-08-07T00:00:00Z',
                type: 'HM',
                seq: '1',
              },
            ],
          },
          employmentDetails: [
            {
              employmentType: {
                type: 'FTM',
                description: 'Full Time Employment',
              },
              occupation: '002',
              jobDescription: 'Professionals',
              employerName: 'Kalq Limited',
              effectiveDate: '2025-08-06T12:00:00.000Z',
              seq: '1',
            },
          ],
          clientCapacity: {
            capacityAssessment: {
              anyExpectedChanges: 'Y',
              changeDetails: 'N',
              assessmentQuestionsAsked: 'Y',
              selfDeclarationAccepted: 'Y',
            },
            joint: 'N',
            assets: [],
            liabilities: [],
            incomes: [],
            expenses: [],
          },
          mode: 'Add',
        },
      },
    },
    {
      type: 'securities',
      id: '0000299612',
      attributes: {
        seq: '1',
        accountSecurity: {
          primaryCollateral: 'P',
          effectiveDate: '2025-04-28T00:00:00Z',
          clientSecurityRelationship: 'O',
        },
        asset: {
          assetType: 'S',
          classificationCode: 'VEHI',
          securityPercentageToUse: '100',
          condition: { code: 'U', description: '' },
          securityStatus: { code: 'C', description: '' },
        },
        vehicleMaint: {
          assetExtras: [],
          vehicle: { value: '0000000000', refType: 'ASSIGN' },
          vehicleDetails: {
            externalSystemReference: '',
            make: '',
            model: '',
            registrationYear: '',
            colour: '',
            nonStandardVehicle: { code: 'Y', description: '' },
            registrationNumber: '',
            odometer: '0',
          },
        },
      },
    },
  ],
}
